# Generated by Django 2.1.7 on 2019-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_personal4'),
    ]

    operations = [
        migrations.CreateModel(
            name='M1301',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('dekidaka', models.IntegerField(blank=True, null=True)),
                ('close_adjust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_1301',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M1332',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('dekidaka', models.IntegerField(blank=True, null=True)),
                ('close_adjust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_1332',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M1333',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('dekidaka', models.IntegerField(blank=True, null=True)),
                ('close_adjust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_1333',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M1352',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('dekidaka', models.IntegerField(blank=True, null=True)),
                ('close_adjust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_1352',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M1376',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('dekidaka', models.IntegerField(blank=True, null=True)),
                ('close_adjust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_1376',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M1377',
            fields=[
                ('date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('dekidaka', models.IntegerField(blank=True, null=True)),
                ('close_adjust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm_1377',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
